<script lang="ts">
	import GettingStarted from '$lib/getting_started.svx';
  import type { DocEntry } from "$lib/doc.ts"
  import API from "$lib/API.svelte"
	import '../../node_modules/prism-themes/themes/prism-dracula.css';

	const docs: DocEntry[] = [
		{
			name: 'Peer',
			tags: ["CONSTRUCTOR"],
			example: 'const peer = new Peer([id], [options]);',
			description: 'A peer can connect to other peers and listen for connections.',
			children: [
				{
					name: '[id]',
					tags: ["STRING"],
					description:
						'Other peers can connect to this peer using the provided ID. If no ID is given, one will be generated by the brokering server. The ID must start and end with an alphanumeric character (lower or upper case character or a digit). In the middle of the ID spaces, dashes (-) and underscores (_) are allowed.',
					warning:
						"It's not recommended that you use this ID to identify peers, as it's meant to be used for brokering connections only. You're recommended to set the <a href=\"#peerconnect-options\"><code>metadata</code></a> option to send other identifying information.",
				},
        {
          name: '[options]',
          tags: ["OBJECT"],
          children: [
            {
              name: 'key',
              tags: ["STRING"],
              description:
                ' API key for the cloud PeerServer. This is not used for servers other than <code>0.peerjs.com</code>',
              warning:
                'PeerServer cloud runs on port 443. Please ensure it is not blocked or consider running your own PeerServer instead.'
            },
            {
              name: 'host',
              tags: ["STRING"],
              description:
                "Server host. Defaults to <code>0.peerjs.com</code>. Also accepts <code>'/'</code> to signify relative hostname."
            },
            {
              name: 'port',
              tags: ["NUMBER"],
              description: 'Server port. Defaults to <code>443</code>'
            },
            {
              name: 'pingInterval',
              tags: ["NUMBER"],
              description: 'Ping interval in ms. Defaults to <code>5000</code>'
            },
            {
              name: 'path',
              tags: ["STRING"],
              description:
                "The path where your self-hosted PeerServer is running. Defaults to <code>'/'</code>."
            },
            {
              name: 'secure',
              tags: ["BOOLEAN"],
              description: "<code>true</code> if you're using SSL.",
              note: 'Note that our cloud-hosted server and assets may not support SSL'
            },
            {
              name: 'config',
              tags: ["OBJECT"],
              description:
                "Configuration hash passed to RTCPeerConnection. This hash contains any custom ICE/TURN server configuration. Defaults to <code>{ 'iceServers': [{ 'urls': 'stun:stun.l.google.com:19302' }], 'sdpSemantics': 'unified-plan' }</code>"
            },
            {
              name: 'debug',
              tags: ["NUMBER"],
              description: `Prints log messages depending on the debug level passed in. Defaults to <code>0</code>.
              <div class="children">
                <div class="child" id="peer-options-debug-0">
                  <span class="name"><a href="#peer-options-debug-0">0</a></span> <span class="ml-2 description">Prints no logs.</span>
                </div>
                <div class="child" id="peer-options-debug-1">
                  <span class="name"><a href="#peer-options-debug-1">1</a></span> <span class="ml-2 description">Prints only errors.</span>
                </div>
                <div class="child" id="peer-options-debug-2">
                  <span class="name"><a href="#peer-options-debug-2">2</a></span> <span class="ml-2 description">Prints errors and warnings.</span>
                </div>
                <div class="child" id="peer-options-debug-3">
                  <span class="name"><a href="#peer-options-debug-3">3</a></span> <span class="ml-2 description">Prints all logs.</span>
                  </div>
                </div>`
            }
          ]
        }
			]
		},
		{
			name: 'peer.connect',
			tags: ["METHOD"],
			example: 'const dataConnection = peer.connect(id, [options]);',
			description:
				'Connects to the remote peer specified by <code>id</code> and returns a data connection. Be sure to listen on the <a href="#peeron-error"><code>error</code></a> event in case the connection fails.',
			children: [
				{
					name: 'id',
					tags: ["STRING"],
					description:
						'The brokering ID of the remote peer (their <a href="#peerid"><code>peer.id</code></a>).',
					children: [
						{
							name: '[options]',
							tags: ["OBJECT"],
							children: [
								{
									name: 'label',
									tags: ["STRING"],
									description:
										'A unique label by which you want to identify this data connection. If left unspecified, a label will be generated at random. Can be accessed with <a href="#dataconnection-label"><code>dataConnection.label</code></a>.'
								},
								{
									name: 'metadata',
									description:
										' Metadata associated with the connection, passed in by whoever initiated the connection. Can be accessed with <a href="#dataconnection-metadata"><code>dataConnection.metadata</code></a>. Can be any serializable type.',
									tags: ["ANY"]
								},
								{
									name: 'serialization',
									tags: ["STRING"],
									description:
										'Can be <code>binary</code> (default), <code>binary-utf8</code>, <code>json</code>, or <code>none</code>. Can be accessed with <a href="#dataconnection-serialization"><code>dataConnection.serialization</code></a>.',
									note: '<code>binary-utf8</code> will take a performance hit because of the way UTF8 strings are packed into binary format'
								},
								{
									name: 'reliable',
									tags: ["BOOLEAN"],
									description:
										'Whether the underlying data channels should be reliable (e.g. for large file transfers) or not (e.g. for gaming or streaming). Defaults to <code>false</code>.',
									warning:
										'Setting reliable to true will use a shim for incompatible browsers (Chrome 30 and below only) and thus may not offer full performance.'
								}
							]
						}
					]
				}
			]
		},
		{
			name: 'peer.call',
			tags: ["METHOD"],
			example: 'const mediaConnection = peer.call(id, stream, [options])',
			description:
				'Calls the remote peer specified by <code>id</code> and returns a media connection. Be sure to listen on the <a href="#peeron-error"><code>error</code></a> event in case the connection fails.',
			children: [
				{
					name: 'id',
					tags: ["STRING"],
					description:
						'The brokering ID of the remote peer (their <a href="#peerid"><code>peer.id</code></a>).'
				},
				{
					name: 'stream',
					tags: ["MEDIASTREAM"],
					description: "The caller's media stream"
				},
				{
					name: '[options]',
					tags: ["OBJECT"],
					children: [
						{
							name: 'metadata',
							tags: ["ANY"],
							description:
								' Metadata associated with the connection, passed in by whoever initiated the connection. Can be accessed with <a href="#dataconnection-metadata"><code>dataConnection.metadata</code></a>. Can be any serializable type.'
						},
						{
							name: 'sdpTransform',
							tags: ["METHOD"],
							description: 'Function which runs before create offer to modify sdp offer message.'
						}
					]
				}
			]
		},
		{
			name: 'peer.on',
			tags: ["METHOD"],
			example: 'peer.on(event, callback)',
			description: 'Set listeners for peer events.',
			children: [
				{
					name: "'open'",
					tags: ["EVENT"],
					example: "peer.on('open', function(id) { ... });",
					description:
						'Emitted when a connection to the PeerServer is established. You may use the peer before this is emitted, but messages to the server will be queued. <code>id</code> is the brokering ID of the peer (which was either provided in the constructor or assigned by the server).',
					note: 'You should not wait for this event before connecting to other peers if connection speed is important.'
				},
				{
					name: "'connection'",
					tags: ["EVENT"],
					example: "peer.on('connection', function(dataConnection) { ... });",
					description: 'Emitted when a new data connection is established from a remote peer'
				},
				{
					name: "'call'",
					tags: ["EVENT"],
					example: "peer.on('call', function(mediaConnection) { ... });",
					description:
						'Emitted when a remote peer attempts to call you. The emitted <code>mediaConnection</code> is not yet active; you must first answer the call (<a href="#mediaconnection-answer"><code>mediaConnection.answer([stream]);</code></a>). Then, you can listen for the <a href="#mediaconnection-on"><code>stream</code></a> event.'
				},
				{
					name: "'close'",
					tags: ["EVENT"],
					example: "peer.on('close', function() { ... });",
					description:
						'Emitted when the peer is <a href="#peerdestroy">destroyed</a> and can no longer accept or create any new connections. At this time, the peer\'s connections will all be closed.',
					note: 'To be extra certain that peers clean up correctly, we recommend calling peer.destroy() on a peer when it is no longer needed.'
				},
				{
					name: "'disconnected'",
					tags: ["EVENT"],
					example: "peer.on('disconnected', function() { ... });",
					description:
						'Emitted when the peer is disconnected from the signalling server, either <a href="#peerdisconnect">manually</a> or because the connection to the signalling server was lost. When a peer is disconnected, its existing connections will stay alive, but the peer cannot accept or create any new connections. You can reconnect to the server by calling <a href="#peerreconnect"><code>peer.reconnect()</code></a>. '
				},
				{
					name: "'error'",
					tags: ["EVENT"],
					example: "peer.on('error', function(err) { ... });",
					description:
						'Errors on the peer are <b>almost always fatal</b> and will destroy the peer. Errors from the underlying socket and PeerConnections are forwarded here.<br/>These come in the following <code>error.type</code> flavors:',
					children: [
						{
							name: "'browser-incompatible'",
							tags: ["ERROR", "FATAL"],
							description:
								"The client's browser does not support some or all WebRTC features that you are trying to use."
						},
						{
							name: "'disconnected'",
							tags: ["ERROR"],
							description:
								"You've already disconnected this peer from the server and can no longer make any new connections on it."
						},
						{
							name: "'invalid-id'",
							tags: ["ERROR", "FATAL"],
							description: 'The ID passed into the Peer constructor contains illegal characters.'
						},
						{
							name: "'invalid-key'",
							tags: ["ERROR", "FATAL"],
							description:
								'The API key passed into the Peer constructor contains illegal characters or is not in the system (cloud server only).'
						},
						{
							name: "'network'",
							tags: ["ERROR"],
							description: 'Lost or cannot establish a connection to the signalling server.'
						},
						{
							name: "'peer-unavailable'",
							tags: ["ERROR"],
							description: "The peer you're trying to connect to does not exist."
						},
						{
							name: "'ssl-unavailable'",
							tags: ["ERROR", "FATAL"],
							description:
								'PeerJS is being used securely, but the cloud server does not support SSL. Use a custom PeerServer.'
						},
						{
							name: "'server-error'",
							tags: ["ERROR", "FATAL"],
							description: 'Unable to reach the server.'
						},
						{
							name: "'socket-error'",
							tags: ["ERROR", "FATAL"],
							description: 'An error from the underlying socket.'
						},
						{
							name: "'socket-closed'",
							tags: ["ERROR", "FATAL"],
							description: 'The underlying socket closed unexpectedly.'
						},
						{
							name: "'unavailable-id'",
							tags: ["ERROR", "SOMETIMES_FATAL"],
							description: 'The ID passed into the Peer constructor is already taken',
							warning:
								'This error is not fatal if your peer has open peer-to-peer connections. This can happen if you attempt to <a href="#peerreconnect">reconnect</a> a peer that has been <a href="#peerdisconnect">disconnected from the server</a>, but its old ID has now been taken.'
						},
						{
							name: "'webrtc'",
							tags: ["ERROR"],
							description: 'Native WebRTC errors'
						}
					]
				}
			]
		},
		{
			name: 'peer.disconnect',
			tags: ["METHOD"],
			example: 'peer.disconnect()',
			description:
				'Close the connection to the server, leaving all existing data and media connections intact. <a href="#peerdisconnected"><code>peer.disconnected</code></a> will be set to <code>true</code> and the <a href="#peeron-disconnected"><code>disconnected</code></a> event will fire.',
			warning:
				'This cannot be undone; the respective peer object will no longer be able to create or receive any connections and its ID will be forfeited on the (cloud) server.'
		},
		{
			name: 'peer.reconnect',
			tags: ["METHOD"],
			example: 'peer.reconnect()',
			description:
				"Attempt to reconnect to the server with the peer's old ID. Only <a href=\"#peerdisconnect\">disconnected peers</a> can be reconnected. Destroyed peers cannot be reconnected. If the connection fails (as an example, if the peer's old ID is now taken), the peer's existing connections will not close, but any associated errors events will fire."
		},
		{
			name: 'peer.destroy',
			tags: ["METHOD"],
			example: 'peer.destroy()',
			description:
				' Close the connection to the server and terminate all existing connections. <a href="#peerdestroyed"><code>peer.destroyed</code></a> will be set to <code>true</code>.',
			warning:
				'This cannot be undone; the respective peer object will no longer be able to create or receive any connections, its ID will be forfeited on the (cloud) server, and all of its data and media connections will be closed.'
		},
		{
			name: 'peer.id',
			tags: ["STRING"],
			description:
				'The brokering ID of this peer. If no ID was specified in <a href="#peer">the constructor</a>, this will be <code>undefined</code> until the <a href="#peeron-open"><code>open</code></a> event is emitted. '
		},
		{
			name: 'peer.connections',
			tags: ["OBJECT"],
			description:
				"A hash of all connections associated with this peer, keyed by the remote peer's ID.",
			note: 'We recommend keeping track of connections yourself rather than relying on this hash.'
		},
		{
			name: 'peer.disconnected',
			tags: ["BOOLEAN"],
			description: '<code>false</code> if there is an active connection to the PeerServer.'
		},
		{
			name: 'peer.destroyed',
			tags: ["BOOLEAN"],
			description: '<code>true</code> if the peer and all of its connections can no longer be used.'
		},
		{
			name: 'DataConnection',
			tags: ["CLASS"],
			description:
				'Wraps WebRTC\'s DataChannel. To get one, use <a href="#peerconnect"><code>peer.connect</code></a> or listen for the <a href="#peeron-connect"><code>connect</code></a> event.',
			children: [
				{
					name: '.send',
					tags: ["METHOD"],
					example: 'dataConnection.send(data)',
					description:
						'<code>data</code> is serialized by BinaryPack by default and sent to the remote peer.',
					children: [
						{
							name: 'data',
							tags: ["ANY"],
							description: 'You can send any type of data, including objects, strings, and blobs.'
						}
					]
				},
				{
					name: '.close',
					tags: ["METHOD"],
					example: 'dataConnection.close()',
					description:
						'Close the connection gracefully, cleaning up underlying DataChannels and PeerConnections'
				},
				{
					name: '.on',
					tags: ["METHOD"],
					example: 'dataConnection.on(event, callback)',
					description: 'Set listeners for data connection events.',
					children: [
						{
							name: "'data'",
							tags: ["EVENT"],
							example: "dataConnection.on('data', function(data) { ... })",
							description: 'Emitted when data is received from the remote peer.'
						},
						{
							name: "'open'",
							tags: ["EVENT"],
							example: "dataConnection.on('data', function(data) { ... });",
							description: 'Emitted when data is received from the remote peer.'
						},
						{
							name: "'close'",
							tags: ["EVENT"],
							example: "dataConnection.on('close', function() { ... });",
							description: 'Emitted when either you or the remote peer closes the data connection.',
							warning: 'Firefox does not yet support this event.'
						},
						{
							name: "'error'",
							tags: ["EVENT"],
							example: "dataConnection.on('error', function(err) { ... });"
						}
					]
				},
				{
					name: '.dataChannel',
					tags: ["OBJECT"],
					description: 'A reference to the RTCDataChannel object associated with the connection.'
				},
				{
					name: '.label',
					tags: ["STRING"],
					description:
						'The optional label passed in or assigned by PeerJS when the connection was initiated.'
				},
				{
					name: '.metadata',
					tags: ["ANY"],
					description:
						'Any type of metadata associated with the connection, passed in by whoever initiated the connection.'
				},
				{
					name: '.open',
					tags: ["BOOLEAN"],
					description: 'This is true if the connection is open and ready for read/write.'
				},
				{
					name: '.peerConnection',
					tags: ["OBJECT"],
					description: 'A reference to the RTCPeerConnection object associated with the connection.'
				},
				{
					name: '.peer',
					tags: ["STRING"],
					description: 'The ID of the peer on the other end of this connection.'
				},
				{
					name: '.reliable',
					tags: ["BOOLEAN"],
					description:
						'Whether the underlying data channels are reliable; defined when the connection was initiated.'
				},
				{
					name: '.type',
					tags: ["STRING"],
					description: "For data connections, this is always <code>'data'</code>."
				},
				{
					name: '.bufferSize',
					tags: ["NUMBER"],
					description:
						'The number of messages queued to be sent once the browser buffer is no longer full.'
				}
			]
		},
		{
			name: 'MediaConnection',
			tags: ["CLASS"],
			description: "Wraps WebRTC's media streams. To get one, use <a href=\"#peercall\"><code>peer.call</code></a> or listen for the <a href=\"#peeron-call\"><code>call</code></a> event.",
			children: [
				{
					name: '.answer',
					tags: ["METHOD"],
					example: 'mediaConnection.answer([stream], [options]);',
          description: "When receiving a <a href=\"#peeron-call\"><code>call</code></a> event on a peer, you can call <code>.answer</code> on the media connection provided by the callback to accept the call and optionally send your own media stream.",
          children: [
            {
              name: '[stream]',
              tags: ["MEDIASTREAM"],
              description: " WebRTC media stream from <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Navigator.getUserMedia\"><code>getUserMedia</code></a>."
            },
            {
              name: "[options]",
              tags: ["OBJECT"],
              children: [
                {
                  name: "sdpTransform",
                  tags: ["METHOD"],
                  description: "Function which runs before create answer to modify sdp answer message."
                }
              ]
            }
          ]
				},
        {
          name: '.close',
          tags: ["METHOD"],
          example: 'mediaConnection.close()',
          description: 'Closes the media connection.'
        },
        {
          name: ".on",
          tags: ["METHOD"],
          example: "mediaConnection.on(event, callback)",
          description: "Set listeners for media connection events.",
          children: [
            {
              name: "'stream'",
              tags: ["EVENT"],
              example: "mediaConnection.on('stream', function(stream) { ... })",
              description: "Emitted when a remote peer adds a <code>stream</code>"
            },
            {
              name: "'close'",
              tags: ["EVENT"],
              example: "mediaConnection.on('close', function() { ... })",
              description: "Emitted when either you or the remote peer closes the media connection.",
              warning: 'Firefox does not yet support this event.'
            },
            {
              name: "'error'",
              tags: ["EVENT"],
              example: "mediaConnection.on('error', function(err) { ... })",
            }
          ]
        },
        {
          name: '.open',
          tags: ["BOOLEAN"],
          description: "Whether the media connection is active (e.g. your call has been answered). You can check this if you want to set a maximum wait time for a one-sided call.", 
        },
        {
          name: '.metadata',
          tags: ["ANY"],
          description: "Any type of metadata associated with the connection, passed in by whoever initiated the connection."
        },
        {
          name: '.peer',
          tags: ["STRING"],
          description: "The ID of the peer on the other end of this connection."
        },
        {
          name: '.type',
          tags: ["STRING"],
          description: "For media connections, this is always <code>'media'</code>."
        }
			]
		},
    {
      name: "util",
      tags: ["OBJECT", "UTILITY"],
      description: "Provides a variety of helpful utilities.",
      warning: "Only the utilities documented here are guaranteed to be present on <code>util</code>. Undocumented utilities can be removed without warning. We don't consider these to be 'breaking changes.'",
      children: [
        {
          name: ".browser",
          tags: ["STRING"],
          example: "if (util.browser === 'Firefox') { /* OK to peer with Firefox peers. */ }",
          description: "The current browser. This property can be useful in determining whether or not two peers can connect. For example, as of now data connections are not yet interoperable between major browsers. <code>util.browser</code> can currently have the values 'Firefox', 'Chrome', 'Unsupported', or 'Supported' (unknown WebRTC-compatible browser)."
        },
        {
          name: ".supports",
          tags: ["OBJECT"],
          example: "if (util.supports.data) { /* OK to start a data connection. */ }",
          description: "A hash of WebRTC features mapped to booleans that correspond to whether the feature is supported by the current browser.",
          warning: "Only the properties documented here are guaranteed to be present on <code>util.supports</code>.",
          children: [
            {
              name: ".audioVideo",
              tags: ["BOOLEAN"],
              description: "True if the current browser supports media streams and PeerConnection."
            },
            {
              name: ".data",
              tags: ["BOOLEAN"],
              description: "True if the current browser supports DataChannel and PeerConnection."
            },
            {
              name: ".binary",
              tags: ["BOOLEAN"],
              description: "True if the current browser supports binary DataChannels."
            },
            {
              name: ".reliable",
              tags: ["BOOLEAN"],
              description: "True if the current browser supports reliable DataChannels."
            }
          ]
        }
      ]
    }
	];
</script>

<section class="start">
	<h1>
		<a href="/">PeerJS</a>
		<span class="title">docs</span>
	</h1>
	<GettingStarted />
</section>

<header class="left">
	<h2>
		API Reference
		<a class="hide icon">&laquo;</a>
		<a class="show icon">&raquo;</a>
	</h2>
</header>
<header class="right">
	<h2>Getting Started</h2>
</header>

<section class="api">

  {#each docs as doc}
    <API {doc} top={true}></API>
  {/each}
</section>
<style global>

  @import '../lato.css';
  html {
    color: #000;
    background: #fff;
  }
  body,
  div,
  dl,
  dt,
  dd,
  ul,
  ol,
  li,
  pre,
  code,
  form,
  fieldset,
  legend,
  input,
  button,
  textarea,
  p,
  blockquote,
  th,
  td {
    margin: 0;
    padding: 0;
  }
  table {
    border-collapse: collapse;
    border-spacing: 0;
  }
  fieldset,
  img {
    border: 0;
  }
  address,
  caption,
  cite,
  code,
  dfn,
  em,
  th,
  var,
  optgroup {
    font-style: inherit;
    font-weight: inherit;
  }
  del,
  ins {
    text-decoration: none;
  }
  li {
    list-style: none;
  }
  caption,
  th {
    text-align: left;
  }
  q:before,
  q:after {
    content: "";
  }
  abbr,
  acronym {
    border: 0;
    font-variant: normal;
  }
  sup {
    vertical-align: baseline;
  }
  sub {
    vertical-align: baseline;
  }
  legend {
    color: #000;
  }
  input,
  button,
  textarea,
  select,
  optgroup,
  option {
    font-family: inherit;
    font-size: inherit;
    font-style: inherit;
    font-weight: inherit;
  }
  input,
  button,
  textarea,
  select {
    font-size: 100%;
  }
  a {
    outline: none;
  } /* Gets rid of Firefox's dotted borders */
  a img {
    border: none;
  } /* Gets rid of IE's blue borders */

  body,
  html {
    font-size: 14px;
    line-height: 24px;
    font-family: "Lato", Helvetica, sans-serif;
    color: #454545;
  }

  header.right,
  header.left {
    cursor: pointer;
    z-index: 100;
    position: fixed;
    top: 0;
    height: 35px;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
  }

  header.left {
    border-bottom: 1px solid rgba(0, 0, 0, 0.1);
    border-right: 4px solid rgba(0, 0, 0, 0.1);
    background-color: #50484e;
    text-align: right;
    left: 0;
    width: 47%;
  }
  header.right {
    border-bottom: 1px solid rgba(0, 0, 0, 0.1);
    border-left: 4px solid rgba(0, 0, 0, 0.1);
    background-color: #eee;
    text-align: left;
    right: 0;
    width: 53%;
  }

  .left h2,
  .right h2 {
    color: #e2a62e;
    letter-spacing: 1px;
    text-transform: uppercase;
    font-size: 14px;
    margin: 0;
    padding: 6px 10px;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2);
  }

  .right h2 {
    color: #5a5157;
    text-shadow: 0 -1px 0 #fff;
  }

  .left .icon {
    color: #e2a62e;
    cursor: pointer;
    font-family: monospace;
    font-size: 20px;
    display: inline-block;
    margin-left: 5px;
  }

  .icon.show {
    display: none;
  }

  .api,
  .start {
    position: absolute;
    top: 0px;
    bottom: 0px;
    overflow-y: scroll;
    overflow-x: hidden;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    transition: left 300ms;
  }

  .api.fullscreen {
    width: 100%;
  }

  .start.full {
    left: 30px;
    width: auto;
  }

  /** hiding */
  .api.hidden {
    left: -370px;
    width: 400px;
    overflow: hidden;
  }

  .api.hidden > div {
    opacity: 0.6;
  }

  .start {
    background-color: #fcfcfc;
    width: 53%;
    right: 0px;
    top: 35px;
    text-shadow: 0px -1px 0 #fff;
    border-top: 1px solid #fff;
    z-index: 99;
    color: #645b61;
  }

  .start h1 {
    margin: 0;
    background-color: #fff;
    font-size: 40px;
    line-height: 40px;
    padding: 30px 20px;
    border-bottom: 1px solid #eee;
    color: #5a5157;
    border-left: 4px solid #ddd;
  }

  /** Code stylings */
  section.start pre {
    font-family: Consolas, Inconsolata, "Bitstream Vera Sans Mono", Menlo, Monaco,
      "Andale Mono", "Courier New", monospace;
    font-size: 12px;
    background-color: #474045;
    border-left: 4px solid #40393e;
    padding: 15px 30px 15px 40px;
    color: #e7e0e5;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.1);
    max-width: 100%;
    overflow: auto;
  }
  /** /code */

  h1 a {
    color: #5a5157;
    text-decoration: none;
    transition: color 300ms;
  }

  h1 a:hover {
    color: #745e6d;
  }

  h1 .title {
    color: #fff;
    display: inline-block;
    font-size: 15px;
    text-transform: uppercase;
    font-variant: small-caps;
    background-color: #e2a62e;
    padding: 2px 4px;
    line-height: 15px;
    border-radius: 2px;
    border: 2px solid rgba(0, 0, 0, 0.2);
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2);
  }

  .start > p,
  .start > div {
    padding: 5px 30px 5px 40px;
    border-left: 4px solid #ddd;
  }

  .start p.red {
    color: #8f4537;
  }

  .start h2,
  .start h3,
  .start h4 {
    color: #5a5157;
    padding: 12px 25px 5px 25px;
    margin: 0;
    font-size: 20px;
    border-left: 4px solid #ccc;
  }

  .start h3 {
    font-size: 15px;
    padding: 12px 25px 5px 25px;
    border-bottom: 1px solid #eee;
  }

  a {
    font-weight: 600;
    color: #1295d8;
    text-decoration: none;
    transition: color 200ms;
  }
  a:hover {
    color: #33a2dc;
  }

  .api {
    color: #f5eff3;
    font-weight: 300;
    top: 35px;
    left: 0px;
    width: 47%;
    border-right: 4px solid #474046;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    background-color: #5a5157;
    text-shadow: 0px -1px 0 #474045;
    z-index: 100;
  }

  .child {
    padding: 10px 0 10px 15px;
  }

  .bracket {
    font-weight: 800;
    display: inline-block;
    margin: 0 2px;
    color: rgba(255, 255, 255, 0.2);
  }

  .toplevel {
    border-bottom: 1px solid rgba(0, 0, 0, 0.1);
    padding: 30px 35px;
  }

  .api:not(:first-child) {
    border-top: 1px solid rgba(255, 255, 255, 0.1);
  }

  .toplevel > .children > .child {
    padding-right: 5px;
  }

  .children {
    border-left: 1px solid rgba(0, 0, 0, 0.1);
  }

  .beta_030 .children {
    border-left: 1px solid rgba(233, 97, 81, 0.5);
  }

  .api div p {
    margin: 0 0 5px 0;
  }

  .child:hover {
    background-color: #635960;
  }

  /** Label stylings */
  .tag {
    display: inline-block;
    background-color: #454545;
    border-radius: 2px;
    color: rgba(255, 255, 255, 0.8);
    line-height: 11px;
    padding: 1px 2px;
    margin-left: 5px;
    font-size: 9px;
    letter-spacing: 1px;
    font-weight: 600;
    font-family: "Lato", Helvetica, sans-serif;
    text-transform: uppercase;
    border: 1px solid rgba(0, 0, 0, 0.4);
    text-shadow: 0px -1px 0px rgba(0, 0, 0, 0.2);
  }

  .toplevel > .name {
    font-size: 20px;
  }

  /** /Label stylings */

  .api .snippet {
    color: #a2949d;
    border-left: 1px solid #40393e;
    border-top: 1px solid #40393e;
    border-right: 1px solid #6b666a;
    border-bottom: 1px solid #6b666a;
    text-shadow: 0 -1px 0 #393438;
    font-size: 12px;
    font-family: Consolas, Inconsolata, "Bitstream Vera Sans Mono", Menlo, Monaco,
      "Andale Mono", "Courier New", monospace;
    font-weight: 400;
    display: inline-block;
    background-color: #474045;
    padding: 3px 8px;
    margin: 5px 0 0 10px;
  }

  /* We want to be able to use the names as an anchor. */
  .api .name {
    font-weight: 600;
    display: inline-block;
    margin-bottom: 5px;
  }

  .name a {
    cursor: pointer;
    color: #fff;
    text-decoration: none;
    transition: color 300ms;
  }

  .name a:hover {
    color: #e7e0e5;
  }
  /* /name */

  .tip,
  .warn {
    opacity: 0.9;
    display: block;
    background-color: #d1c7be;
    font-size: 13px;
    line-height: 18px;
    border-radius: 2px;
    padding: 5px 8px;
    border: 2px solid rgba(0, 0, 0, 0.2);
    margin: 8px 8px 0 0;
  }

  .warn {
    background-color: #8f4537;
  }
  .tip {
    color: #544e4a;
    text-shadow: 0px -1px 0px rgba(255, 255, 255, 0.2);
    font-weight: 600;
  }

  #peer-options-debug .child {
    padding: 0 15px;
  }

  #peer-options-debug .child .description {
    display: inline-block;
    margin-left: 10px;
  }

  .start code,
  .api code {
    font-family: Consolas, Inconsolata, "Bitstream Vera Sans Mono", Menlo, Monaco,
      "Andale Mono", "Courier New", monospace;
    border-radius: 2px;
    border: 1px solid rgba(255, 255, 255, 0.2);
    background: rgba(255, 255, 255, 0.1);
    font-size: 12px;
    padding: 2px;
  }

  .start > .two-col {
    padding-left: 0;
    padding-right: 0;
  }
  .two-col .col {
    float: left;
    width: 50%;
  }

  .two-col .col.col-header {
    font-weight: 600;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    padding-left: 20px;
    padding-right: 20px;
  }

  .clear {
    clear: both;
  }
</style>